### ISSUE TITLE
"phyint" command does not reenable vifs after "disable-vifs"

### ISSUE THREAD

**Issue by jp-t** [troglobit/pimd#100]
a configuration file like:
```
disable-vifs
...
phyint eth0 enable igmpv3 dr-priority 1 ttl-threshold 1
```
leaves eth0 disabled.

This is due to the "token" variable being overwritten before use while reading the "phyint" line in the first pass.
So, only the "disable-vifs" indication is used while creating the vif list from the kernel, resulting in no interface available at all.

I'm preparing a patch.

**Comment by troglobit** [comment]
Ah ... yeah the file parser has some rough edges.  Thank you for taking the time to report and fix this!
