### ISSUE TITLE
No status log

### ISSUE THREAD

**Issue by shengliu8833** [troglobit/pimd#136]
Hi Joachim,
It looks like there is a problem to build and install the PIMD:
./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var
There is a message: Skipping unknown option: localstatedir
And we cannot see any log file for PIMD in /var except the /var/run/pimd/pimd.dump
Any idea?
Thank you,
Sheng

**Comment by troglobit** [comment]
Works here, what version of pimd are you trying this command with?  The README shown on GitHub is for the master branch which contains yet to be released software, including the new build system.

Please consult the README for the version of pimd you are trying to build, it holds the relevant documentation.

**Comment by shengliu8833** [comment]
Nevermind, got it working with 2.3.2. Thanks.

**Comment by troglobit** [comment]
OK :)
