### ISSUE TITLE
register_vif forced to igmpv3

### ISSUE THREAD

**Issue by Kzibi** [troglobit/pimd#142]
It's not(?) the issue - just question.

pimctl -i pimd_jambox show igmp int 
Interface         State     Querier          Timeout Version  Groups                                                                                 
epix_sgt_kat      Up        172.24.3.12          265       2       0
epix_sgt_waw      Up        172.24.1.12          345       2       0
jambox_down       Up        Local               None       2      32
register_vif0     Up        Local               None       3       0 

Why register_vif is force to igmp v3
vif.c :
void zero_vif(struct uvif *v, int t)
{
    v->uv_flags><------>= 0;<-->/* Default to IGMPv3 */

**Comment by troglobit** [comment]
What do you mean?

**Comment by Kzibi** [comment]
All interfaces uses igmp v2 (configured in pimd.conf),  except vif0, which is igmp v3.
I prefer to all of them have igmp v2. 
How can I set it ?

**Comment by troglobit** [comment]
@Kzibi not possible to configure atm., but I'm leaning towards disabling IGMP altogether on the register VIF since it shouldn't be needed there. Must check the RFC's first, however, to see if I'm missing something obvious.

**Comment by troglobit** [comment]
I've looked into this now.  Turns out this is only a minor issue with pimctl reporting the IGMP version of all interfaces when in fact pimd always avoids IGMP altogether on the register interface.

I'll fix pimctl and close this.
