### ISSUE TITLE
Publish docker image

### ISSUE THREAD

**Issue by gclawes** [troglobit/pimd#147]
I've created a PR (#146) with a Dockerfile that builds pimd/pimctl and packages them in a debian:stretch image.  Can this be published to https://hub.docker.com/u/troglobit

**Comment by gclawes** [comment]
This Dockerfile let me build the latest tag (2.3.2), as well:

```
FROM debian:stretch

COPY . /root/pimd
WORKDIR /root/pimd
RUN apt-get update && apt-get install -y build-essential automake git
RUN ./configure --prefix=/usr
RUN make

FROM debian:stretch
COPY --from=0 /root/pimd/pimd /usr/sbin/

CMD [ "/usr/sbin/pimd", "--foreground" ]
```

**Comment by troglobit** [comment]
Cool, thanks man! 

Any particular reason you chose debian and not alpine?

**Comment by gclawes** [comment]
Switched to alpine.  Here's an updated Dockerfile to manually build version 2.3.2:

```
FROM alpine:3.9

COPY . /root/pimd
WORKDIR /root/pimd
RUN apk add --update build-base automake autoconf linux-headers git
RUN ./configure --prefix=/usr --sysconfdir=/etc
RUN make

FROM alpine:3.9
COPY --from=0 /root/pimd/pimd /usr/sbin/
COPY --from=0 /root/pimd/pimd.conf /etc

CMD [ "/usr/sbin/pimd", "--foreground" ]
```

**Comment by troglobit** [comment]
Neat, thank you!  I guess you want both the 2.3.2 and latest master on dockerhub, right?

**Comment by gclawes** [comment]
Yeah, both would be good.  It's up to you if you want `:latest` to mean latest commit or latest tag (I've seen both in the docker world), but I don't see a tag anywhere for the `3.0-beta1` version.

**Comment by gclawes** [comment]
I've seen some places use `:latest` for latest-tag, and either `:master` or `:snapshot` for latest-commit.

**Comment by troglobit** [comment]
Ah, overloaded term of course ... snapshot is perhaps the best then. 

(We currently don't tag intermediate versions like beta or RC in this project.)

**Comment by troglobit** [comment]
Pushed.  Hopefully it works to your liking.  I had to modify the (above) Dockerfile for v2.3.2 quite heavily since we didn't have autoconf-based configure script back then, and we also used GIT submodules for some BSD replacement functions.

**Comment by gclawes** [comment]
Thanks! Since `:2.3.2` is the latest tag, can you push that to `:latest` as well so `docker pull troglobit/pimd` works properly?

```
$ docker pull troglobit/pimd
Using default tag: latest
Error response from daemon: manifest for troglobit/pimd:latest not found
```

**Comment by troglobit** [comment]
Sure, fixed.
