### ISSUE TITLE
Possible to disable IGMPv2 Querier message generation?

### ISSUE THREAD

**Issue by bewing** [troglobit/pimd#158]
I am testing deploying pimd to facilitate distribution of existing, working network/bare metal PIM-SM multicast into docker containers inside hosts.  During my testing, due to the legacy setup of our datacenters, I noticed an interesting behavior.  Simplified, our topology is thus:

```
   +-----+----+
   |  MCAST   |
   |  SEND A  |
   |          |
   +----+-----+
        |
        |
   +----v-----+   vLAN /w IGMPv2 SNOOPING
   |  Router  +-----------+----------------+
   |    B     |           |                |
   |   .254   |     +-----v----+     +-----v----+
   +---+------+     |  MCAST   |     | PIM HOST |
                    |  RCVR C  |     |    D     |
                    |    .10   |     |   .20    |
                    +----------+     +----------+
```
We have host `A` generating hello messages to 100 different multicast groups, and host `C` subscribing to all 100 groups.

Before starting pimd on host `D`, Router `B` is the mrouter and IGMPv2 querier for the vLAN, and multicast is only flooded to host `C` in the vLAN.

After starting pimd on host `D`, it establishes a PIM-SM neighborship with router `B`, and due to its lower last octet, is elected the IGMPv2 querier.  Now, all 100 groups are no longer pruned from host `D`, as he has to hear all multicast replies to the query message.  This can cause multiple problems:

* As we add more hosts, listening to different mcast groups to the vLAN, we can run into head of line blocking issues, as the PIM host will subscribe to the superset of all mcast groups on the vLAN
* The kernel rapidly fills its 10-slot mroute cache, running us straight into #58 when we have docker containers on the host start to request mcast.

By longstanding convention, we IP bare-metal hosts according to the U they are in a rack, which means .1 is usually not available to assign the Switch/Router `B`.

Can we force the PIM daemon to not participate in the querier election?  Is it the sending of the IGMPv2 membership query message that causes this issue? Or is just speaking PIM-SM at all with a lower IP going to cause other PIM routers to not generate IGMPv2 membership query messages?

**Comment by bewing** [comment]
On further investigation, it looks like an architecture change is the real solution.  From RFC3488:

```
   The main limitation of IGMP Snooping is that it can only restrict
   multicast traffic onto switch ports where receiving hosts are
   connected directly or indirectly via other switches.  IGMP Snooping
   can not restrict multicast traffic to ports where at least one
   multicast router is connected.  It must instead flood multicast
   traffic to these ports.  Snooping on IGMP messages alone is an
   intrinsic limitation.  Through it, a switch can only learn which
   multicast flows are being requested by hosts.  A switch can not learn
   through IGMP which traffic flows need to be received by router ports
   to be routed because routers do not report these flows via IGMP.
```
Closing issue.

**Comment by troglobit** [comment]
Glad you found the answer you needed. In general, however, there's no point to disabling IGMP query in router since that's the way hosts (including switches) learn where the router is located so they can forward their streams to it, so the router can forward it on another LAN if needed.
