### ISSUE TITLE
Support for SSM via DNS

### ISSUE THREAD

**Issue by eKrajnak** [troglobit/pimd#162]
It would be great to have implementation for SSM via DNS. Cisco, Juniper, ... have implementations already. Described in draft 

> https://tools.ietf.org/html/draft-schoch-dns-ssm-00

**Comment by troglobit** [comment]
This looks like a convention for end devices, not routing daemons. Specifically, section 3 details the steps for resolving a channel, and subscribes (using IGMP) to the (S,G) IP address pairs resolved using DNS.

The pimd routing daemon does not have any support for acting as an end device, so I'm inclined to close this issue as non-applicable. 

Comments?

**Comment by troglobit** [comment]
No feedback, closing.
