### ISSUE TITLE
Socket path and other options not possible when building packages. 

### ISSUE THREAD

**Issue by LouisAtGH** [troglobit/pimd#163]
The problem with the socket path I had, is related to packages. After significant debugging the problem is clear. 

When you build pimd using the GNU-tools, you set options like e.g. “./configure --localstatedir=/var”. After that you generate a distribution file. 

Then you start the packet builder, who is doing the building work again. ..... However (nearly) without options ……  So it builds the defaults! and that is not always OK! The workaround I use is to install the package and then override the executables with the good ones.

The long term solution I am thinking about, is to store options “persistent” in the build system. The alternative, doing extremely complicated things in “ports” (probably not even possible!!), is not a good idea. Not only because of the complexity, but it also implies maintaining things twice and it has to be invent things for every type of package builder.

Louis

**Comment by troglobit** [comment]
I'm sorry, but this is not a problem with the build system of pimd, but a problem in how you build packages.  There already exist mechanisms for caching previously called arguments to the configure script. Closing.
