### ISSUE TITLE
PIMD package should be target system independent (e.g. in regard MAXVIFS)

### ISSUE THREAD

**Issue by LouisAtGH** [troglobit/pimd#181]
In my option a package should, **as a goal**, be target system independent. I know that is never 100% possible.

So back to the MAXVIFS example

In the actual situation the correct PIMD behavoir depends on the MAXVIFS settings:
- in "ip_mroute.h" on the development machine
- "ip_mroute.h" on the target system
- the settings is configure.ac
- the  ./configure call ( --with-max-vifs=^xx^)
- the settings in the ports make file (CONFIGURE_ARGS+= --localstatedir=/var --with-max-vifs=^xx^

IMHO that is wrong and makes the package **target-system-settings** depended, which is IMHO very bad !! 

I am not 100% sure it is possible, but what should IMHO the solution is:
- start pimd
- ask the OS for its actual maxvifs number
- create the needed struct-arrays using the maxvifs as obtained from the OS
- do the "pimd-job" 

Of course there is history, and multiple os, etc 

Never the less,

Louis

**Comment by troglobit** [comment]
Remember #178?  That was the last straw for me, really. After that I (as sole maintainer of the project), explicitly changed the status of other operating systems from equal status to Linux to *not supported anymore*.  Meaning, I as maintainer will not spend any more time on breaking my back trying to support them.

This is stated plain as day in the README now:

> pimd is primarily developed on Linux and should work as-is out of the box on all major distributions.
> Other UNIX variants (OpenBSD, NetBSD, FreeBSD, and Illumos) may also work, but are **not supported anymore**.

For over 10 years I had the goal to support other systems and be as independent as possible. But I cannot do it alone and *will not* let other people dictate what are goals for my own project.  If you do not agree with this, there's a button on top called "Fork" that you can press and then start maintaining and supporting all the systems you like.
