### ISSUE TITLE
Question：the same ip of the router && Drop package at the beginning 

### ISSUE THREAD

**Issue by zcauto** [troglobit/pimd#208]

**Comment by zcauto** [comment]
Hello，

In a certain scenario, I encountered a problem！
The topology is as follows：
                                                                                                pc2 192.168.1.2
                                                                                                                                                                                   |
pc1（192.168.1.1) -  router1（192.168.1.234）- router2(192.168.253.1) - router3(192.168.253.2) -  router4(192.168.1.234)                                         
                                                                                                                              |
                                                                                                              router5(192.168.253.3   rp) - router6(192.168.1.234)
                                                                                                                                                                                  |
                                                                                                                                                                 pc3 192.168.1.3
the router5 is rp.  There are routes between pc1, pc2, pc3, router2, router3, router5。but the router1、router4、router6 have the same ip。      When pc3 joins the multicast 225.3.2.1, when pc1 starts to send packets, it will drop about 100 packets ，and later packets will be received。    The RPT tree can be built, but the spt tree cannot be built at first. I don't know what the problem is?

**Comment by ruckc** [comment]
If you have duplicate IP addresses in the network, its very unlikely your going to get PIM routing to work, especially if your running network address translation.

**Comment by zcauto** [comment]
In fact, if I change the ip to a different one, there may be serious packet drops. Is pimd not suitable for wireless routing scenarios? In addition, when the PC has multiple network cards, it may not receive data packets.

**Comment by troglobit** [comment]
The above image is garbled and very hard to make out what your problem is, have you tried applying some Markdown markup to put your ASCII art in verbatim mode?
