### ISSUE TITLE
HELP: IGMP monitoring tool

### ISSUE THREAD

**Issue by lars18th** [troglobit/pimd#245]
Hi @troglobit ,

I know that this is not the correct place to make a question not directly related to this tool. However, I'm tired searching for a "simple" solution and I feel you can help me. Sorry if you don't accept this use of the issues section.

My problem is to get a tool that can listen for the IGMP Host Reports in my LAN (that is multicast-aware using the IGMP Snoopig). I want to start/stop a process (than generates the multicast traffic) based on the presence of multicast listeners. It seems to me that such a tool might be easy to find, but it is not. You know about something similar?

Thank you and sorry for this post.

**Comment by troglobit** [comment]
This is more of a discussion, so I'm moving it there.
