### ISSUE TITLE
multiple static rp addresses 

### ISSUE THREAD

**Issue by nav60** [troglobit/pimd#248]
Hi,
I need assistance automatic switch between static rp-addresses in pimd. I have seen similar functionality in Fortinet multicast setting. It support multiple static rp addresses and switch wen message is received from the mapping agent. However, pimd only consider first rp address as the main rp-address and switching to next rp address is not possible. Any suggestion or guidance please.

**Comment by troglobit** [comment]
The current behavior of pimd is, I believe, documented well.  Patches to support more features, according to open standards, are always welcome.

**Comment by nav60** [comment]
ok Sir.
As per my understanding Fortinet implementation parses the auto-rp (mapping messages) to get current RP-address and update the user given list accordingly.  
Thanks

**Comment by nav60** [comment]
Please close it.

**Comment by troglobit** [comment]
@nav60 but why?

**Comment by nav60** [comment]
Actually, as per my working using pimd tool, it does not provide parsing of auto-RP mapping agent message which contain RP-address. In my case, i want to switch between two rp's of my network which are statically defined in the pimd.conf.  PIMD does not support this case. Another issue is that if i manage pimd.conf file using some script based on parsing of mapping-agent message, due to unknown reason, mapping agent message disappeared on WAN interface once pimd using old RP-address. Its mean that mapping agent message stopped once RP-address is defined in the pimd.conf. It is possible that my understanding is wrong now i am checking other possible ways to implement this concept.
