### ISSUE TITLE
Add support for Cisco style "ip pim register-source"

### ISSUE THREAD

**Issue by troglobit** [troglobit/pimd#38]
Thomas Lau of Tetrion Captial Ltd writes:

> On Cisco router I could use ip pim register-source to specific
> which source IP / interface should I use to "announce" to neighbor,
> but I can't see this option exists on PIMD, may I know how could I
> implement this? ​

**Comment by troglobit** [comment]
You can probably add this functionality if you hack
the following two functions in `pim_proto.c`:

    send_pim_register()
    send_pim_null_register()

I imagine the following setting in pimd.conf:

    register_source <ifname>

Which can be used to find the `vifi_t` in the above
functions. Notice how both the IP address and the
MTU is read from the `vifi_t`.

**Comment by 42wim** [comment]
Would be nice if ```phyint 1.2.3.4 enable``` would actually use 1.2.3.4 and not the first ip found on that interface. 

We're using keepalived and the virtual ip address should be the one used. As workaround i'm now hardcoding the ip addresses.

**Comment by troglobit** [comment]
@42wim Sounds more than reasonable.  The code isn't prepared for that today, unclear even if the code can actually handle multiple addresses on interfaces.  

I can have a look at this later, unless you beat me to it.

**Comment by troglobit** [comment]
Should be fixed in 5a53406. Note, to use this it is recommended to start `pimd` with `-N` flag:

    pimd -N -c noif.conf

and selectively enable interfaces in the .conf file:

    phyint virbr0 enable
    phyint gre0 enable
    phyint 192.168.1.42 enable

If an interface has multiple addresses, `pimd` will now only use the one selected.  In this case `192.168.1.42` of `usb0`.

**Comment by 42wim** [comment]
cool! Thanks for the work.

**Comment by troglobit** [comment]
World be awesome if someone could test it before we release it :)

**Comment by 42wim** [comment]
I'll try in the week of 12 june :-)

**Comment by troglobit** [comment]
Thanks man! 😎✌️
