### ISSUE TITLE
/var/run/pimd/pimd.dump: No such file or directory

### ISSUE THREAD

**Issue by greenpau** [troglobit/pimd#45]
Occasionally, when i issue the below command, I get the following error:

```
# pimd -r
cat: /var/run/pimd/pimd.dump: No such file or directory
#
```

**Comment by troglobit** [comment]
Yeah, little bit fragile implementation.  With '-r' the `pimd` client sends a signal to the background `pimd` server process and then sleeps for a short while.  When the client wakes up it expects the file to be there.

On a reasonably loaded system the pimd server process may not yet have had time to cater to the signal and generate the file.

This should definitely be reworked.   In the meantime, and as a workaround, you can:

   1. Remove the dump file
   2. Send the signal manually
   3. Wait for the file to be created
   4. Display file

**Comment by greenpau** [comment]
@troglobit, thank you for the workaround!
