### ISSUE TITLE
make throws "has no member named ‘mfcc_rp_addr’" error

### ISSUE THREAD

**Issue by greenpau** [troglobit/pimd#47]
Configuring and then compiling:

```
./configure --enable-scoped-acls --enable-kernel-encap --enable-memory-save --enable-kernel-mfc
```

and receive the following error:

```
# make
  CC      kern.o
kern.c: In function ‘k_chg_mfc’:
kern.c:446:7: error: ‘struct mfcctl’ has no member named ‘mfcc_rp_addr’
     mc.mfcc_rp_addr.s_addr = rp_addr;
       ^
make: *** [kern.o] Error 1
#
```

without `--enable-kernel-encap` builds just fine.

**Comment by troglobit** [comment]
From `./configure --help`:

    --enable-kernel-encap     Some kernels can do PIM Register encapsulation by
                              themselves, this speeds up processing considerably
                              Only enable this if your kernel supports it

I've clarified that message a bit in f1c697a.  Not even sure any kernel ever merged that multicast feature ... as far as I can see the proposed patch was only ever ported to FreeBSD and SunOS many moons ago ...
