### ISSUE TITLE
Force sending join/prune when there are no neighbors?

### ISSUE THREAD

**Issue by amluto** [troglobit/pimd#54]
I have a PIM setup that runs over a one-way GRE tunnel with a static RP configured.  As far as I know, everything should work, except that pimd never sees Hello from the other end because the tunnel only carries outgoing traffic.

Can pimd be taught to send multicast join/prune messages even though it doesn't see any neighbors?

**Comment by troglobit** [comment]
As far as I know, no. The multicast messages passed between the routers is there to figure out what to forward between them ... you also need the unicast routes setup, e.g. with OSPF or similar.

**Comment by amluto** [comment]
This would only work in the case where no one's actually sending encapsulated data.

In any event, it turns out that I tweaked my tunnel config, and all is well.  I'll close this.
