### ISSUE TITLE
Default config uses "/etcpimd.conf" instead of "/etc/pimd.conf"

### ISSUE THREAD

**Issue by amluto** [troglobit/pimd#55]
This bit in Makefile is probably the culprit.

    sysconfdir   ?= /etc
    [...]
    CPPFLAGS     += -D_PATH_SYSCONF=\"$(sysconfdir)\"

Compare to pathnames.h:

    #ifndef _PATH_SYSCONF
    #define _PATH_SYSCONF           "/etc/"
    #endif
    
    #define _PATH_PIMD_CONF         _PATH_SYSCONF "pimd.conf"

Note that explicitly setting --sysconfdir=/etc works fine:

            sysconfdir)
                echo "sysconfdir    = $arg/" >> $TMP
                ;;

On a related note, "sysconfidir" in the configure help text is a typo.

**Comment by troglobit** [comment]
Thanks for the report, will submit a fix soon!

**Comment by troglobit** [comment]
Fixed in 475e0d1
