### ISSUE TITLE
the "./configure" problem

### ISSUE THREAD

**Issue by peacefill** [troglobit/pimd#76]
I have downloaded pimd-2.3.2.tar.gz to my Fedora. After decompression,I run "./configure",then I got"FIXDEP  libite/lite.h missing ... fatal: Not a git repository.FAILED!  No Internet access?" What should I do?

**Comment by troglobit** [comment]
Oups, that shouldn't happen with released tarballs! Did you really download the correct file, or was it one of the GitHub (Source code) download links?

This is the correct one
- https://github.com/troglobit/pimd/releases/download/2.3.2/pimd-2.3.2.tar.gz

I just verified that it works by downloading to my Ubuntu 16.04. It configures and builds without a hitch.

GitHub fumbles quite badly when it comes to repositories that use GIT sub-modules. When I tag a release they create automated download links, like the "Download ZIP" button on the front page of each project. Unfortunately these automated download links do not contain the source for the sub-modules.  Their bad links are usually called:

- 2.3.2.zip,
- 2.3.2.tar.gz, or
- master.zip

**Comment by troglobit** [comment]
For the v2.4 series I plan to redo both configure and the GIT sub-modules. Migrate to pure autoconf/a

**Comment by peacefill** [comment]
I downloaded from another link.Problem solved...Thanks for your help

**Comment by troglobit** [comment]
@peacefill Phew, good to hear! :+1:
