### ISSUE TITLE
pimd.conf for vlans

### ISSUE THREAD

**Issue by Lokotito** [troglobit/pimd#86]
Need some help with pimp.conf
I was trying to use pimd inside my ubiquiti edge router, installed 2.1.8 version from debian repo.
I was trying to multicast UPNP/DLNA serviio fmy vlan1 to vlan3 and vlan4.

eth1: serviio IP 192.168.10.9 (vlan1 192.168.10.0/24)
eth1.3: Clients 192.168.12.0/24 (vlan3)
eth1.4: Clients 192.168.13.0/24 (vlan4)

(UBIQUITI eth1)
|
(LINKSYS L2 Switch) 
|
|--> serviio (vlan1)
| --> clients (vlan4)
| --> clients (vlan3)

serviio sends the traffic to 239.255.255.0.
use the default pimd.conf, just disabling vlan6  and pppoe0 (eth0).

`phyint pppoe0 disable
phyint eth0 disable
phyint eth1.6 disable
cand_rp time 30 priority 20
cand_bootstrap_router priority 5
group_prefix 224.0.0.0 masklen 4`

But I can't have multicast traffic in vlan3 or vlan4. Using tcpdump can't see vlan3 or valn4 didn't receive multicast traffic from SERVIIO.

Is there a parameter that I missed ?
can you help me with a tip please?

Thanks in advance.

**Comment by troglobit** [comment]
First of all, packaged software in distributions is the responsibility of that distribution. The pimd version in Debian is *very* old and I cannot support that old software.

That said, have you checked the TTL of the data you're trying to route?  With multicast that is the most common gotcha.  Second to that is the MULTICAST interface flag on the interfaces.

**Comment by Lokotito** [comment]
that was fast :)
will check booth, also will check if can compile the most recent version to use in ubnt.

I'll come back if have any question.

Thanks.

**Comment by troglobit** [comment]
OK, good luck!

**Comment by Lokotito** [comment]
Installed 2.3.1,
Using default pimd.conf (for 2.3.1 version)
```
phyint eth0 disable
phyint pppoe0 disable
phyint eth1.6 disable
bsr-candidate priority 5
rp-candidate time 30 priority 20
spt-threshold packets 0 interval 100
```


Acording to wire shark TTL for serviio is 31 or 32
and the flags for Mutlicast interface is
192.168.10.9 (Serviio) -> 239.255.255.250
```Flags: 0x00
0... .... = Reserved bit: Not set
    .0.. .... = Don't fragment: Not set
    ..0. .... = More fragments: Not set
```
But have I don't have mutlicast in vlan3 or vlan4.
I'm doing something wrong ?

**Comment by troglobit** [comment]
Well, can you run `tcpdump` inside the router, on the `vlan1` interface?

All three VLAN interfaces need to have the MULTICAST flag set, otherwise pimd will skip them.  Look at your PC for instance with `ifconfig`, the loopback interface `lo` usually does not have MULTICAST, but regular interfaces like `eth0` do. 

There is some more debug help in the included documentation, e.g. [README-debug.md](https://github.com/troglobit/pimd/blob/master/README-debug.md) and my [multicast howto](http://troglobit.com/multicast-howto.html) ... but you're on an embedded system, with a built-in switch as well, so it's not always easy to understand limitations and quirks used there.

**Comment by Lokotito** [comment]
Installed in a Debian Jessie pc, and setup a serviio upnp server. 
With default pimd.conf serviio can send the NOTIFY traffic (with adress) and can see serviio in vlan2, vlan3, vlan4, vlan5 in my network, I'm not sure why in vlan1 can't see serviio.

Try to install pimd in serviio server jail in nas4free (based in freebsd), but I have an error when I try to run:
```
root@ServIIO:/ # pimd -d
debug level 0xffffffff (dvmrp_detail,dvmrp_prunes,dvmrp_routes,dvmrp_neighbors,dvmrp_timers,igmp_proto,igmp_timers,igmp_members,trace,timeout,packets,interfaces,kernel,cache,rsrr,pim_detail,pim_hello,pim_register,pim_join_prune,pim_bootstrap,pim_asserts,pim_cand_rp,pim_routes,pim_timers,pim_rpf)
15:51:41.630 pimd version 2.3.2 starting ...
15:51:41.631 Failed creating IGMP socket in init_igmp(): m
```

I follow the [http://troglobit.com/howto-run-pimd-on-freebsd.html](url) guide but still get same error.

**Comment by troglobit** [comment]
So it works in Debian but not in the nas4free? You need basic multicast and
multicast routing support in the kernel. Cannot really tell more since the
log is cut short.

**Comment by Lokotito** [comment]
Yes, with a test pc (debian  jessie + pimd) multicast traffic can be present in vlans. So I assume that having both, runing in same machine, I will have serviio working in all vlnas.

But installing pimd in my main router (ubiquiti) and having serviio behind a L2 switch L2, I can't get a working multicast.

I think (read in net) that Nas4Free have multicast support in kernel, but will ask in N4F forums, and if have some news will post it.
