### ISSUE TITLE
2 new options for pimd

### ISSUE THREAD

**Issue by Kzibi** [troglobit/pimd#90]
I think it will be usefull  (e.g. in linux name spaces):
1. pid file location/name : e.g. pimd --pidfile /var/run/pimd/xxx/pimd.pid
2. syslog-name  in pimd.conf : e.g. syslog-name "pimd iptv1"

btw.
I test last 2.4 beta ( 08.02.2017) - it's very fast ;)))

**Comment by troglobit** [comment]
The UNIX way of doing this is to expose an `-I, --ident=NAME` that can then be used for `/etc/NAME.conf`, `/var/run/NAME.pid`, and syslog.  That's the first thing.  Adding a custom path to the PID file as well, can be added as well. 

I've already done this for my Inadyn project, so porting both those features should be a straight forward job.

**Comment by troglobit** [comment]
Fixed in 2cf0f3d for v2.4.  

However, note that spaces in the identity string is not allowed.
