### ISSUE TITLE
Arbitrary 15 sec delay before static RP entries are added

### ISSUE THREAD

**Issue by troglobit** [troglobit/pimd#97]
Jean-Pierre Tosoni emailed me, on Thu, Jun 15:
> I am using pimd and I noticed a 15 seconds delay at startup before adding preconfigured RP entries.
> Code:
> Main.c line 543: if (n > boottime + 15) {
> 
> I decreased the delay (even downto zero) and it still seems to work fine and start faster.
> But I’m afraid of missing some synchronization requirement.
> Can you explain the reason behind this delay?

Well, I cannot for the life of me understand why we need that arbitrary 15 sec.  Also, I really could not for the life of me seem to find when this code was added. Took a while of sifting through old commits ... turns out it was the addition of static RP config support, `rp-address `,  added as part of a Debian patch, Jan 16, 2010: GIT hash 5aa52b74c

So many questions ...

**Comment by troglobit** [comment]
Having looked at the code some more, it was evident that there was no reason for keeping the 15 sec delay.  Also, by plain code audit, it was evident that any changes to `rp-address` on `SIGHUP` was not being registered, nor was old `rp-address` entries removed ...

**Comment by jp-t** [comment]
Thank for that!
