### ISSUE TITLE
phyint eth0 scoped 224.0.1.0/24 igmpv2 - igmpv2 ignored

### ISSUE THREAD

**Issue by lunn** [troglobit/pimd#98]
When `parse_phyint()` processes the configuration line

    phyint eth0 scoped 224.0.1.0/24 igmpv2

It ignores the `igmpv2`. The problem here is that after parsing `scoped 224.0.1.0/24` it does
`EQUAL((w = next_word(&s)), "masklen"` to see if there is an optional `masklen`, which i don't have. This is consuming the `igmpv2` option, so it never gets parsed.

Probably the simple fix here is to only look for masklen `if !scoped_masklen`.

The `altnet` option probably has the same issue, although i didn't test it.

**Comment by troglobit** [comment]
Thanks for the heads-up @lunn, will look into it right away!

**Comment by troglobit** [comment]
There, should be fixed now.  Will be released as part of the upcoming major v3.0.
Please reopen this issue should the problem persist.

Thank you again for the report, and thank you for your amazing work on kernel DSA!
(Tobias sends his regards :smiley: )
